### ISSUE TITLE
Move optimizer libraries to extra requirements

### ISSUE THREAD

**Issue by NeoChaos12** [PhMueller/HPOlibExperimentUtils#1]
Given the nature of the repo, I believe it should be possible (and well worth the effort) to write code such that there is no need to install all the optimizers that it supports in order to run it and only install the ones that are needed. This is of particular relevance now that I'm including Dragonfly code in the development branch. I believe that if we shift the respective imports to the respective 'run' methods, it should suffice.

**Comment by NeoChaos12** [comment]
Another alternative is to move each optimizer to its own module and import the modules only when needed.

**Comment by PhMueller** [comment]
Sounds good! Iike the second idea more. Is this okay for you? But to be honest I don't have a particular reason for this approach :smile: 

Then I would do it as soon as possible.

**Comment by PhMueller** [comment]
Commit 3be78ee4640c9f4a32471b85e02040ea169889c4 includes the desired changes.

**Comment by NeoChaos12** [comment]
I think this would be necessary if you don't want to install and set up dragonfly just in order to avoid import errors. Likewise, I would prefer to avoid installing SMAC unless I actually need to use it.
